### ISSUE TITLE
Add payment  connection from ModuleBank

### ISSUE THREAD

**Issue by kurakoff** [kurakoff/lk_sizze#6]
https://dev.modulbank.ru/download/attachments/917526/modulbank-payment-gate-api-1.2.pdf?version=5&modificationDate=1545728349270&api=v2

**Comment by kot6egemot** [comment]
Магазин создан? Или там для теста есть?

**Comment by kurakoff** [comment]
Магазин не открыли - надо подтверждение. Для теста посмотрю.
